export const MENUITEMS = [
  {
    menutitle: "DASHBOARD",
    Items: [
      // {
      //   path: `/dashboard`,
      //   icon: "ti-home",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "Dashboard",
      // },
      {
        path: `/pages/categories`,
        type: "link",
        icon: "fas fa-th-list",

        active: false,
        selected: false,
        title: "Categories",
      },
      {
        path: `/pages/tages`,
        type: "link",
        icon: "fas fa-tags",

        active: false,
        selected: false,
        title: "Tags",
      },
      {
        path: `/pages/training`,
        type: "link",
        icon: "fas fa-chalkboard-teacher",

        active: false,
        selected: false,
        title: "Trainings",
      },
      {
        path: `/pages/settingspage`,
        type: "link",
        icon: "fas fa-cog",

        active: false,
        selected: false,
        title: "Settings",
      },
      // {
      //   path: `/pages/images`,
      //   type: "link",
      //   icon: "ti-list",

      //   active: false,
      //   selected: false,
      //   title: "Images",
      // },
      {
        path: `/pages/projects`,
        type: "link",
        icon: "fas fa-project-diagram",

        active: false,
        selected: false,
        title: "Projects",
      },
      {
        path: `/pages/publications`,
        type: "link",
        icon: "fas fa-book",

        active: false,
        selected: false,
        title: "Publications",
      },
      {
        path: `/pages/ourpartners`,
        type: "link",
        icon: "fas fa-handshake",

        active: false,
        selected: false,
        title: "OurPartners",
      },
      {
        path: `/pages/linkes`,
        type: "link",
        icon: "fas fa-link",

        active: false,
        selected: false,
        title: "Linkes",
      },
      {
        path: `/pages/contactus`,
        type: "link",
        icon: "fas fa-envelope",

        active: false,
        selected: false,
        title: "ContactUs",
      },
      {
        path: `/pages/users`,
        type: "link",
        icon: "fas fa-users",

        active: false,
        selected: false,
        title: "Users",
      },

      {
        path: `/pages/authors`,
        type: "link",
        icon: "fas fa-user",

        active: false,
        selected: false,
        title: "Authors",
      },

      {
        path: `/pages/contacts`,
        type: "link",
        icon: "fas fa-address-book",

        active: false,
        selected: false,
        title: "Contacts",
      },
      {
        path: `/pages/questions`,
        type: "link",
        icon: "far fa-list-alt",

        active: false,
        selected: false,
        title: "Questions",
      },

      {
        path: `/pages/uploadimage`,
        type: "link",
        icon: "fas fa-file-upload",

        active: false,
        selected: false,
        title: "uploadimage",
      },

      
      // {
      //   title: "ECommerce",
      //   icon: "ti-shopping-cart-full",
      //   type: "sub",
      //   active: false,
      //   selected: false,
      //   children: [
      //     {
      //       path: `/ecommerce/ecdashboard`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Dashboard",
      //     },
      //     {
      //       path: `/ecommerce/products`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Products",
      //     },
      //     {
      //       path: `/ecommerce/productdeatils`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Product Details",
      //     },
      //     {
      //       path: `/ecommerce/eccart`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Cart",
      //     },
      //     {
      //       path: `/ecommerce/wishlist`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Wishlist",
      //     },
      //     {
      //       path: `/ecommerce/cheackout`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Checkout",
      //     },
      //     {
      //       path: `/ecommerce/order`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Orders",
      //     },
      //     {
      //       path: `/ecommerce/addproduct`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Add Product",
      //     },
      //     {
      //       path: `/ecommerce/account`,
      //       type: "link",
      //       active: false,
      //       selected: false,
      //       title: "Account",
      //     },
      //   ],
      // },
    ],
  },
  //   {
  //     menutitle: "LANDINGPAGE",
  //     Items: [
  //       {
  //         path: `/landingpage`,
  //         icon: "ti-layout",
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         title: "Landingpage",
  //       },
  //     ],
  //   },
  // {
  //   menutitle: "APPILICATION",
  //   Items: [
  //     {
  //       title: "Apps",
  //       icon: "ti-write",
  //       type: "sub",
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `/apps/widgets`,
  //           icon: "ti-server",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Widgets",
  //         },
  //         {
  //           title: "Mail",
  //           icon: "ti-email",
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `/apps/mail/mailinbox`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Mail-Inbox",
  //             },
  //             {
  //               path: `/apps/mail/viewmail`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "View-Mail ",
  //             },
  //             {
  //               path: `/apps/mail/mailcomposed`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Mail-Composed ",
  //             },
  //           ],
  //         },
  //         {
  //           title: "Maps",
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `/apps/maps/leafletsmaps`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Leaflet Maps",
  //             },
  //             {
  //               path: `/apps/maps/rsmmaps`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Rsm Maps",
  //             },
  //           ],
  //         },
  //         {
  //           title: "Tables",
  //           icon: "ti-agenda",
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `/apps/table/reactbasictables`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Basic Tables",
  //             },
  //             {
  //               path: `/apps/table/reactdatatables`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Data Tables",
  //             },
  //           ],
  //         },
  //         {
  //           title: "Blog",
  //           icon: "ti-agenda",
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `/apps/blog/blog`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog",
  //             },
  //             {
  //               path: `/apps/blog/blogdetails`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog-details",
  //             },
  //             {
  //               path: `/apps/blog/blogpost`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Blog-post",
  //             },
  //           ],
  //         },
  //         {
  //           title: "File Manager",
  //           icon: "ti-agenda",
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `/apps/file/filemanger`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "File-manager",
  //             },
  //             {
  //               path: `/apps/file/filemangerlist`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "File-manager-list",
  //             },
  //             {
  //               path: `/apps/file/filedetails`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "File-details",
  //             },
  //             {
  //               path: `/apps/file/fileattachements`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "FileAttachements",
  //             },
  //           ],
  //         },
  //         {
  //           title: "Icons",
  //           icon: "ti-agenda",
  //           type: "sub",
  //           active: false,
  //           selected: false,
  //           children: [
  //             {
  //               path: `/icons/fontawesome`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Font Awesome",
  //             },
  //             {
  //               path: `/icons/materialdesignicons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Material Design icons",
  //             },
  //             {
  //               path: `/icons/simplelineicons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Simple Line icons",
  //             },
  //             {
  //               path: `/icons/feathericons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Feather icons",
  //             },
  //             {
  //               path: `/icons/ionicicons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Ionic icons",
  //             },
  //             {
  //               path: `/icons/flagsicons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Flags icons",
  //             },
  //             {
  //               path: `/icons/pe7icons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Pe7 icons",
  //             },
  //             {
  //               path: `/icons/themifyicons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Themify icons",
  //             },
  //             {
  //               path: `/icons/typiconsicons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Typicons icons",
  //             },
  //             {
  //               path: `/icons/weathericons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Weather icons",
  //             },
  //             {
  //               path: `/icons/materialicons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Material icons",
  //             },
  //             {
  //               path: `/icons/bootsrapicons`,
  //               type: "link",
  //               active: false,
  //               selected: false,
  //               title: "Bootstrap icons",
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  // },

  // {
  //   menutitle: "COMPONENTS",
  //   Items: [
  //     {
  //       title: "Elements",
  //       icon: "ti-package",
  //       type: "sub",
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `/elements/alerts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Alerts",
  //         },
  //         {
  //           path: `/elements/accordions`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Accordion",
  //         },
  //         {
  //           path: `/elements/avatars`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Avatar",
  //         },
  //         {
  //           path: `/elements/breadcrumbs`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Breadcrumbs",
  //         },
  //         {
  //           path: `/elements/buttons`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Buttons",
  //         },
  //         {
  //           path: `/elements/badges`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Badge",
  //         },
  //         {
  //           path: `/elements/dropdown`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Dropdown",
  //         },
  //         {
  //           path: `/elements/thumbnails`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Thumbnails",
  //         },
  //         {
  //           path: `/elements/listgroups`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "List Group",
  //         },
  //         {
  //           path: `/elements/navigation`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Navigation",
  //         },
  //         {
  //           path: `/elements/paginations`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Pagination",
  //         },
  //         {
  //           path: `/elements/popovers`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Popover",
  //         },
  //         {
  //           path: `/elements/progress`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Progress",
  //         },
  //         {
  //           path: `/elements/spinner`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Spinners",
  //         },
  //         {
  //           path: `/elements/mediaobjects`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Media Object",
  //         },
  //         {
  //           path: `/elements/typographys`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Typography",
  //         },
  //         {
  //           path: `/elements/tooltips`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Tooltip",
  //         },
  //         {
  //           path: `/elements/tabs`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Tabs",
  //         },
  //         {
  //           path: `/elements/toasts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Toast",
  //         },
  //         {
  //           path: `/elements/tags`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Tags",
  //         },
  //       ],
  //     },
  //     {
  //       title: "AdvancedUI",
  //       icon: "ti-briefcase",
  //       type: "sub",
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `/advanceUI/chat`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Chat",
  //         },
  //         {
  //           path: `/advanceUI/cards`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "cards",
  //         },
  //         {
  //           path: `/advanceUI/calendar`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Calendar",
  //         },
  //         {
  //           path: `/advanceUI/contacts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Contacts",
  //         },

  //         {
  //           path: `/advanceUI/carousels`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Carousel",
  //         },
  //         {
  //           path: `/advanceUI/collapse`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Collapse",
  //         },
  //         {
  //           path: `/advanceUI/modals`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Modals",
  //         },
  //         {
  //           path: `/advanceUI/timeline`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Timeline",
  //         },

  //         {
  //           path: `/advanceUI/sweetalert`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Sweet Alert",
  //         },
  //         {
  //           path: `/advanceUI/rating`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Ratings",
  //         },
  //         {
  //           path: `/advanceUI/search`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Search",
  //         },
  //         {
  //           path: `/advanceUI/userlist`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Userlist",
  //         },
  //         {
  //           path: `/advanceUI/notifications`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Notification",
  //         },
  //         {
  //           path: `/advanceUI/treeview`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Tree-view",
  //         },
  //       ],
  //     },
  //   ],
  // },

  // {
  //   menutitle: "OTHER PAGES",
  //   Items: [
  //     {
  //       title: "Pages",
  //       icon: "ti-palette",
  //       type: "sub",
  //       menutitle: "",
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `/pages/profile`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Profile",
  //         },
  //         {
  //           path: `/pages/aboutus`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Aboutus",
  //         },
  //         {
  //           path: `/pages/notificationlist`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Notificationlist",
  //         },
  //         {
  //           path: `/pages/settings`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Settings",
  //         },

  //         {
  //           path: `/pages/invoice`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Invoice",
  //         },
  //         {
  //           path: `/pages/faq`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Faqs",
  //         },
  //         {
  //           path: `/pages/pricingtable`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Pricing",
  //         },
  //         {
  //           path: `/pages/gallery`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Gallery",
  //         },
  //         {
  //           path: `/pages/messagesuccess`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Success Message",
  //         },
  //         {
  //           path: `/pages/messagedanger`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Danger Message",
  //         },
  //         {
  //           path: `/pages/messagewarning`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Warning Message",
  //         },
  //         {
  //           path: `/pages/emptypage`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Empty Page",
  //         },
  //         {
  //           path: `/pages/switcherpages`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Switcher Page",
  //         },
  //       ],
  //     },

  //     {
  //       title: "Utilities",
  //       icon: "ti-shield",
  //       type: "sub",
  //       children: [
  //         {
  //           path: `/utilities/background`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Background",
  //         },
  //         {
  //           path: `/utilities/border`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Border",
  //         },
  //         {
  //           path: `/utilities/display`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Display",
  //         },
  //         {
  //           path: `/utilities/flex`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Flex",
  //         },
  //         {
  //           path: `/utilities/height`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Height",
  //         },
  //         {
  //           path: `/utilities/margin`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Margin",
  //         },
  //         {
  //           path: `/utilities/padding`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Padding",
  //         },
  //         {
  //           path: `/utilities/position`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Position",
  //         },
  //         {
  //           path: `/utilities/width`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Width",
  //         },
  //         {
  //           path: `/utilities/extras`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Extras",
  //         },
  //       ],
  //     },
  //     {
  //       title: "Authentication",
  //       icon: "ti-lock",
  //       type: "sub",
  //       children: [
  //         {
  //           path: `/custompages/signin`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Sign In",
  //         },
  //         {
  //           path: `/custompages/signup`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Sign Up",
  //         },
  //         {
  //           path: `/custompages/forgotpassword`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Forgot Password",
  //         },
  //         {
  //           path: `/custompages/resetpassword`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Reset Password",
  //         },
  //         {
  //           path: `/custompages/underConstruction`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " UnderConstruction",
  //         },
  //         {
  //           path: `/custompages/lockscreen`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Lockscreen",
  //         },
  //         {
  //           path: `/custompages/error404`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Error404",
  //         },
  //         {
  //           path: `/custompages/error505`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: " Error505",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   menutitle: "FORMS & CHARTS",
  //   Items: [
  //     {
  //       title: "Forms",
  //       icon: "ti-receipt",
  //       type: "sub",
  //       badge: "badge bg-info side-badge",
  //       badgetxt: "7",
  //       background: "hor-rightangle",
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `/forms/formelements`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Elements",
  //         },
  //         {
  //           path: `/forms/advancedforms`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Advanced Forms",
  //         },
  //         {
  //           path: `/forms/formlayout`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Layouts",
  //         },
  //         {
  //           path: `/forms/formvalidation`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Validation",
  //         },
  //         {
  //           path: `/forms/formwizard`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form wizards",
  //         },
  //         {
  //           path: `/forms/formeditor`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Editor",
  //         },
  //         {
  //           path: `/forms/formelementssizes`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Form Element-sizes",
  //         },
  //       ],
  //     },

  //     {
  //       title: "Charts",
  //       icon: "ti-bar-chart",
  //       type: "sub",
  //       badge: "badge bg-danger side-badge",
  //       badgetxt: "5",
  //       background: "hor-rightangle",
  //       badge1: true,
  //       active: false,
  //       selected: false,
  //       children: [
  //         {
  //           path: `/charts/chartjs`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Chartjs",
  //         },
  //         {
  //           path: `/charts/echart`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Echart",
  //         },
  //         {
  //           path: `/charts/nvd3charts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Nvd3charts",
  //         },
  //         {
  //           path: `/charts/c3barcharts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "C3barcharts",
  //         },
  //         {
  //           path: `/charts/piacharts`,
  //           type: "link",
  //           active: false,
  //           selected: false,
  //           title: "Piacharts",
  //         },
  //       ],
  //     },
  //   ],
  // },
];
