name: Build and Deploy

on:
  push:
    branches:
      - main # Change to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: docker/cache-action@v2
        with:
          path: |
            ~/docker-cache
            /usr/share/nginx/html

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/react-app:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/react-app:cache,mode=max

      - name: Deploy to server (Optional)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem username@server_ip 'docker-compose pull && docker-compose up -d'
